"""Create producers table

Revision ID: e5cc618e385d
Revises: 
Create Date: 2025-06-26 11:20:45.665755

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5cc618e385d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('total_area_hectares', sa.Float(), nullable=False),
    sa.Column('arable_area_hectares', sa.Float(), nullable=False),
    sa.Column('vegetation_area_hectares', sa.Float(), nullable=False),
    sa.Column('planted_crops', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_cpf_cnpj'), 'producers', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_producers_id'), 'producers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producers_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_cpf_cnpj'), table_name='producers')
    op.drop_table('producers')
    # ### end Alembic commands ###
